// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffDBContext_Code_first;

namespace StaffDBContext_Code_first.Migrations
{
    [DbContext(typeof(StaffContext))]
    partial class StaffContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StaffDBContext_Code_first.Model.DTO.PositionDbDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("StaffDBContext_Code_first.Model.DTO.StaffDbDto", b =>
                {
                    b.Property<int>("ServiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceNumber");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("StaffDBContext_Code_first.Model.DTO.StaffPositionDbDto", b =>
                {
                    b.Property<int>("StaffNumber")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<float>("Bet")
                        .HasColumnType("real");

                    b.HasKey("StaffNumber", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("StaffPosition");

                    b.HasCheckConstraint("CK_StaffPosition_Bet", "Bet >= 0 AND Bet <= 1");
                });

            modelBuilder.Entity("StaffDBContext_Code_first.Model.DTO.StaffPositionDbDto", b =>
                {
                    b.HasOne("StaffDBContext_Code_first.Model.DTO.PositionDbDto", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffDBContext_Code_first.Model.DTO.StaffDbDto", "Staff")
                        .WithMany("Positions")
                        .HasForeignKey("StaffNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("StaffDBContext_Code_first.Model.DTO.StaffDbDto", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
