CREATE TABLE [dbo].[StaffPosition]
(
	[StaffNumber] INT NOT NULL FOREIGN KEY REFERENCES Staff(ServiceNumber) ON DELETE NO ACTION ON UPDATE NO ACTION,
	[PositionId] INT NOT NULL FOREIGN KEY REFERENCES Position(Id) ON DELETE NO ACTION ON UPDATE NO ACTION,
	[Bet] REAL NOT NULL DEFAULT 1 CHECK (Bet >= 0 AND Bet <= 1),
	PRIMARY KEY (StaffNumber, PositionId)
)
